=== aleavitlax/ordinario-ftw/xml/recetas.dtd
<!ELEMENT recetas (receta+)>

<!ELEMENT receta
(id,nombre,categoria,tiempo,ingredientes,imagen,modo_preparacion)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT modo_preparacion (#PCDATA)>

=== aleavitlax/ordinario-ftw/xml/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "recetas.dtd">
<recetas>

    <receta>
        <id>1</id>
        <nombre>Pizza</nombre>
        <categoria>Comida rápida</categoria>
        <tiempo>25 min</tiempo>
        <ingredientes>Queso, salsa, pepperoni</ingredientes>
        <imagen>imagenes/pizza.avif</imagen>
        <modo_preparacion>
        Paso 1: Preparar la masa
        Activar la levadura: En un recipiente, mezcla el agua tibia, 
        el azúcar y la levadura. Deja reposar de 5 a 10 minutos hasta que salgan burbujas.
        Mezclar: En un bol grande, pon la harina y haz un hueco en el centro. Vierte la levadura activada, 
        el aceite de oliva y la sal por los bordes (evita que la sal toque directamente la levadura). 
        Mezcla todo hasta formar una masa integrada.
        Amasar: Pasa la masa a una superficie plana y amasa con firmeza durante 8 a 10 minutos hasta que
        quede suave, elástica y no se pegue a tus manos.
        Fermentación: Forma una bola con la masa, colócala en un bol ligeramente aceitado y cúbrela con un paño húmedo. 
        Deja reposar en un lugar cálido durante 1 hora, o hasta que duplique su tamaño.
        Paso 2: Armar la pizza
        Estirar: Pasado el tiempo de reposo, aplasta la masa suavemente para quitarle el aire y divídela si quieres
        hacer varias pizzas. Estírala sobre una superficie enharinada con un rodillo o con tus manos hasta obtener el 
        grosor deseado.
        Salsa: Coloca la masa estirada en una bandeja para hornear y esparce una capa uniforme de salsa de tomate, dejando los bordes libres.
        Toppings: Agrega una buena capa de queso mozzarella y distribuye tus ingredientes 
        favoritos por encima.
        Paso 3: HornearPrecalentar: Precalienta el horno a temperatura máxima (idealmente entre 220°C y 250°C) durante unos 20 minutos.
        Cocción: Hornea la pizza durante 8 a 12 minutos. Sabrás que está lista cuando los bordes estén dorados y crujientes, y 
        el queso esté completamente derretido y burbujeante.
        </modo_preparacion>
    </receta>

    <receta>
        <id>2</id>
        <nombre>Hamburguesa</nombre>
        <categoria>Comida rápida</categoria>
        <tiempo>40 min</tiempo>
        <ingredientes>Pan brioche, jitomate, mayonesa, sal, queso, carne de res</ingredientes>
        <imagen>imagenes/hamburguesa.jpg</imagen>
        <modo_preparacion>
       Dora el pan: Unta un poco de mantequilla en el interior de los panes y colócalos en un sartén 
       o plancha a fuego medio hasta que estén ligeramente tostados y acaramelados. Retíralos.
       Cocina la carne: Calienta el sartén o plancha a fuego alto. 
       Agrega un chorrito de aceite y pon la carne. Cocina unos 3 minutos sin moverla para que se forme 
       una costra deliciosa.
       Voltea y pon el queso: Dale la vuelta a la hamburguesa y coloca inmediatamente la rebanada de queso encima.
       Tapa el sartén por un par de minutos para que el queso se derrita a la perfección.
       Arma tu hamburguesa: Coloca la carne con el queso sobre la base del pan. Agrega el tocino crujiente,
       vegetales, salsas al gusto y cubre con la tapa del pan.
        </modo_preparacion>
        
    </receta>

     <receta>
        <id>3</id>
        <nombre>Hot dog</nombre>
        <categoria>Comida rápida</categoria>
        <tiempo>35 min</tiempo>
        <ingredientes>Pan brioche, jitomate, mayonesa, sal, queso, salchicha, catsup</ingredientes>
        <imagen>imagenes/hotDog.webp</imagen>
        <modo_preparacion>
       1. Prepara las salchichas
       Estilo norteño/tocino: Envuelve cada salchicha en espiral con una tira de tocino. 
       Fríelas a fuego medio en un sartén (sin aceite) hasta que el tocino esté crujiente y bien dorado.
       2. Calienta el pan
       Abre los panecillos por la mitad y úntales un poco de mantequilla. Colócalos boca abajo en el mismo 
       sartén donde cocinaste el tocino o las salchichas por unos segundos hasta que estén suaves y ligeramente tostados.
       3. Arma tu hot dog
       Unta el interior del pan con mayonesa al gusto. Coloca la salchicha y añade tus aderezos
    </modo_preparacion>
        
    </receta>

    <receta>
        <id>3</id>
        <nombre>Pastel de Chocolate</nombre>
        <categoria>Postre</categoria>
        <tiempo>60 min</tiempo>
        <ingredientes>Chocolate, harina, huevo</ingredientes>
        <imagen>imagenes/pastel.jpg</imagen>
        <modo_preparacion>
       Precalentar y preparar: Precalienta el horno a 180°C (350°F). Engrasa y enfarina un molde para pastel, o coloca papel para hornear en el fondo.

        Mezclar ingredientes secos: En un tazón grande, cierne y mezcla la harina, el azúcar, la cocoa, el polvo para hornear, el bicarbonato de sodio y la sal hasta que queden completamente integrados.

        Agregar ingredientes líquidos: Añade los huevos, la leche, el aceite y la esencia de vainilla al tazón de los secos. Bate a velocidad media con una batidora eléctrica (o con un batidor de globo) durante unos 2 minutos, hasta obtener una masa homogénea y sin grumos.

        Incorporar el agua caliente: Reduce la velocidad de la batidora al mínimo y vierte poco a poco la taza de agua hirviendo. No te asustes si la mezcla se vuelve muy líquida, es completamente normal y es el secreto para que quede extra suave.

        Hornear: Vierte la masa con cuidado en el molde preparado y hornea durante 35 a 40 minutos. Sabrás que está listo cuando al insertar un palillo en el centro, este salga limpio.

        Enfriar y servir: Saca el pastel del horno y déjalo enfriar en el molde durante 10 minutos. Después, desmóldalo sobre una rejilla para que se enfríe por completo antes de decorarlo con tu cobertura favorita o ganache de chocolate.
    </modo_preparacion>
        
    </receta>
     

    <receta>
        <id>4</id>
        <nombre>Limonada</nombre>
        <categoria>Bebida</categoria>
        <tiempo>10 min</tiempo>
        <ingredientes>Limón, agua, azúcar</ingredientes>
        <imagen>imagenes/limonada.webp</imagen>
        <modo_preparacion>
            Paso a paso Exprime: Lava bien los limones y extrae todo su jugo. 
            Retira las semillas para evitar que la bebida se amargue.
            Disuelve: En una jarra grande, vierte el jugo de limón y añade el azúcar. 
            Remueve bien hasta que los cristales se disuelvan por completo.
            Mezcla: Agrega el agua fría a la jarra y vuelve a remover.
            Enfría: Añade los cubitos de hielo y,si lo deseas, decora con unas rodajas de 
            limón o unas hojas de menta fresca
        </modo_preparacion>
    </receta>
    <receta>
        <id>5</id>
        <nombre>Lasagna</nombre>
        <categoria>Italiana</categoria>
        <tiempo>45 min</tiempo>
        <ingredientes>Láminas de pasta para lasaña, 500g de carne molida, 400g de salsa de tomate, 300g de queso mozzarella, 100g de queso parmesano, cebolla, ajo, sal y pimienta al gusto.</ingredientes>
        <imagen>imagenes/lasagna.jpg</imagen>
        <modo_preparacion>
            1. Sofreír la cebolla y el ajo picados en una sartén con aceite, añadir la carne molida y cocinar hasta que dore. 
            2. Agregar la salsa de tomate, sazonar con sal y pimienta, y dejar hervir a fuego lento por 10 minutos. 
            3. En un molde para horno, colocar una capa de salsa, una capa de láminas de pasta, más salsa de carne y una capa de queso mozzarella. Repetir el proceso hasta llenar el molde. 
            4. Cubrir con queso parmesano y hornear a 180°C durante 25 minutos hasta que el queso esté bien derretido y dorado.
        </modo_preparacion>
        
    </receta>

    <receta>
        <id>6</id>
        <nombre>Cheesecake</nombre>
        <categoria>Postre</categoria>
        <tiempo>60 min</tiempo>
        <ingredientes>200g de galletas de vainilla, 90g de mantequilla derretida, 600g de queso crema, 300ml de crema para batir, 150g de azúcar, 1 cucharadita de esencia de vainilla, 4 hojas de gelatina (o grenetina).</ingredientes>
        <imagen>imagenes/cheesecake.jpg</imagen>
        <modo_preparacion>
            1. Triturar las galletas hasta hacerlas polvo, mezclarlas con la mantequilla derretida y compactar la masa en el fondo de un molde desmontable. Congelar por 10 minutos. 
            2. En un tazón grande, batir el queso crema con el azúcar y la esencia de vainilla hasta obtener una mezcla suave sin grumos. 
            3. Hidratar la gelatina en agua fría, disolverla en un poco de crema tibia y añadirla a la mezcla de queso junto con el resto de la crema batida, integrando de forma envolvente. 
            4. Verter la mezcla sobre la base de galletas y refrigerar por un mínimo de 4 a 6 horas (preferiblemente toda la noche) hasta que cuaje firmemente antes de desmoldar.
        </modo_preparacion>
        
    </receta>

    <receta>
        <id>7</id>
        <nombre>Mojito</nombre>
        <categoria>Bebida</categoria>
        <tiempo>10 min</tiempo>
        <ingredientes>10 hojas de hierbabuena fresca, 1 limón (cortado en cuartos), 2 cucharadas de azúcar, 2 oz de ron blanco, agua mineral con gas, hielo picado al gusto.</ingredientes>
        <imagen>imagenes/mojito.jpg</imagen>
        <modo_preparacion>
            1. En un vaso alto, colocar los cuartos de limón, las hojas de hierbabuena y el azúcar. 
            2. Utilizar un mortero para machacar suavemente los ingredientes en el fondo del vaso, liberando el jugo del limón y los aceites esenciales de la hierbabuena sin romper las hojas. 
            3. Agregar el hielo picado hasta llenar casi todo el vaso y verter las 2 onzas de ron blanco. 
            4. Rellenar el espacio restante con agua mineral con gas, mezclar suavemente de abajo hacia arriba con una cuchara larga y decorar con una ramita extra de hierbabuena.
        </modo_preparacion>
        
    </receta>
    <receta>
        <id>8</id>
